### ISSUE TITLE
Fix VEP filter

### ISSUE THREAD

**Issue by dhspence** [genome/docker-basespace_chromoseq#31]
We're missing some gene variants in TP53 because they apparently have population AF >= 0.001. We should switch the VEP filter string to:

--filter "(MAX_AF < 0.001 or not MAX_AF) or (SOMATIC and (CLIN_SIG is pathogenic or CLIN_SIG is likely_pathogenic))"

I tested this and it works.

**Comment by johnegarza** [comment]
Fixed in dbd9d47 and added to the v12 repo tag/docker image
